Repository AY2021S1-CS2103-T14-4/tp, pull requests merged in 2020-11, with the labels that each got.

#213 Update UG to remove inconsistency
  docs/UserGuide.md
Labels: bug

#214 Update UG to remove wrong example
  docs/UserGuide.md
Labels: bug

#215 Update UG to include optional parameter
  docs/UserGuide.md
Labels: type.documentation

#219 Work on parser test
  src/main/java/tp/acecs2103/logic/commands/ListCommand.java
  src/main/java/tp/acecs2103/logic/parser/AddCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DeadlineCommandParser.java
  src/test/java/tp/acecs2103/logic/parser/AddCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/ArgumentMultimapTest.java
  src/test/java/tp/acecs2103/logic/parser/ArgumentTokenizerTest.java
  src/test/java/tp/acecs2103/logic/parser/CliSyntaxTest.java
  src/test/java/tp/acecs2103/logic/parser/DeadlineCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/DeleteCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/DoneCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/EditCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/FilterCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/FindCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/GetCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/HelpCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/ListCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/ParserUtilTest.java
  src/test/java/tp/acecs2103/logic/parser/PrefixTest.java
  src/test/java/tp/acecs2103/logic/parser/TaskListParserTest.java
  src/test/java/tp/acecs2103/logic/parser/UndoneCommandParserTest.java
Labels: type.test

#221 Create PPP
  docs/team/onglijin.md
Labels: type.documentation

#228 Fix bug of default low resolution and incomplete task box
  docs/UserGuide.md
  src/main/java/tp/acecs2103/commons/core/GuiSettings.java
  src/main/java/tp/acecs2103/model/ModelManager.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/java/tp/acecs2103/ui/TaskBox.java
  src/main/resources/view/CategoryBox.fxml
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.css
  src/main/resources/view/TaskBox.fxml
Labels: bug

#229 Fix bug of alternate colors for list cell empty
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.css
Labels: bug

#230 Fix bug of alternate colors for list cell empty
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.css
Labels: bug

#231 Add add command test and list command test
  src/test/java/tp/acecs2103/logic/parser/AddCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/DoneCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/EditCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/ListCommandParserTest.java
  src/test/java/tp/acecs2103/storage/JsonAdaptedTask.java
Labels: enhancement

#232 Add add command test and list command test
  src/test/java/tp/acecs2103/logic/parser/AddCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/DoneCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/EditCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/ListCommandParserTest.java
  src/test/java/tp/acecs2103/storage/JsonAdaptedTask.java
Labels: enhancement

#239 Parser Tests Phase 1
  docs/team/unicornjin.md
  src/main/java/tp/acecs2103/logic/commands/DeadlineCommand.java
  src/main/java/tp/acecs2103/logic/commands/DoneCommand.java
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/commands/ExitCommand.java
  src/main/java/tp/acecs2103/logic/commands/FilterCommand.java
  src/main/java/tp/acecs2103/logic/commands/GetCommand.java
  src/main/java/tp/acecs2103/logic/commands/HelpCommand.java
  src/main/java/tp/acecs2103/logic/commands/HomeCommand.java
  src/main/java/tp/acecs2103/logic/commands/ListCommand.java
  src/main/java/tp/acecs2103/logic/commands/UndoneCommand.java
  src/main/java/tp/acecs2103/logic/parser/ArgumentTokenizer.java
  src/main/java/tp/acecs2103/logic/parser/FilterCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/Prefix.java
  src/main/java/tp/acecs2103/model/task/CustomizedDeadline.java
  src/main/java/tp/acecs2103/model/task/Deadline.java
  src/main/java/tp/acecs2103/model/task/Description.java
  src/main/java/tp/acecs2103/model/task/OfficialDeadline.java
  src/main/java/tp/acecs2103/model/task/Remark.java
  src/main/java/tp/acecs2103/model/task/WeekNumber.java
  src/test/java/tp/acecs2103/logic/parser/CliSyntaxTest.java
  src/test/java/tp/acecs2103/logic/parser/DeadlineCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/EditCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/FilterCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/GetCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/HelpCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/ParserUtilTest.java
  src/test/java/tp/acecs2103/logic/parser/PrefixTest.java
  src/test/java/tp/acecs2103/logic/parser/TaskListParserTest.java
  src/test/java/tp/acecs2103/logic/parser/UndoneCommandParserTest.java
  src/test/java/tp/acecs2103/storage/JsonAdaptedTaskTest.java
Labels: type.test

#241 Create PPP
  docs/team/unicornjin.md
Labels: type.documentation

#242 Use some assertion
  src/main/java/tp/acecs2103/logic/parser/FindCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ListCommandParser.java
Labels: enhancement

#243 Update JavaDoc for parser part
  src/main/java/tp/acecs2103/logic/parser/CliSyntax.java
  src/main/java/tp/acecs2103/logic/parser/DeadlineCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DoneCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/FilterCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/GetCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/HelpCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ListCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/UndoneCommandParser.java
Labels: type.documentation

#244 Unicorn jin patch 1
  src/main/java/tp/acecs2103/logic/parser/CliSyntax.java
  src/main/java/tp/acecs2103/logic/parser/DeadlineCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DoneCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/FilterCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/GetCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/HelpCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ListCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/UndoneCommandParser.java
Labels: type.documentation

#248 Add ppp
  docs/team/gao-gui.md
Labels: enhancement

#250 Change ppp name
  docs/team/Perpetual09.md
  src/main/java/tp/acecs2103/commons/core/GuiSettings.java
Labels: enhancement

#251 Change ppp name
  docs/team/perpetual09.md
Labels: enhancement

#252 Change ppp name
  docs/team/perpetual09.md
Labels: enhancement

#253 Add more Parser Test, but filter still have bugs
  src/main/java/tp/acecs2103/logic/commands/FilterCommand.java
  src/main/java/tp/acecs2103/logic/parser/AddCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DeadlineCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DeleteCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DoneCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/FilterCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/UndoneCommandParser.java
  src/main/java/tp/acecs2103/model/task/Index.java
  src/test/java/tp/acecs2103/logic/parser/AddCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/ArgumentMultimapTest.java
  src/test/java/tp/acecs2103/logic/parser/ArgumentTokenizerTest.java
  src/test/java/tp/acecs2103/logic/parser/DeadlineCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/DeleteCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/EditCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/FilterCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/GetCommandParserTest.java
Labels: type.test

#259 Improve Ui styling
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Style.css
  src/main/resources/view/TaskBox.css
  src/main/resources/view/TaskBox.fxml
Labels: enhancement

#264 Add testing code until EditCmd, Update UG Ui pictures
  docs/UserGuide.md
  docs/images/w13.png
  docs/images/w6.png
  src/main/java/tp/acecs2103/commons/core/GuiSettings.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Style.css
  src/main/resources/view/TaskBox.fxml
  src/test/java/tp/acecs2103/logic/parser/DeadlineCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/DeleteCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/DoneCommandParserTest.java
  src/test/java/tp/acecs2103/logic/parser/EditCommandParserTest.java
Labels: enhancement

#265 Readd ppp
  docs/team/perpetual09.md
Labels: enhancement

#266 Readd ppp
  docs/team/perpetual09.md
Labels: enhancement

#267 Add hyper link for ppp
  docs/team/perpetual09.md
Labels: enhancement

#268 Add hyper link for ppp
  docs/team/perpetual09.md
Labels: enhancement

#277 Fix documentation issues
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AceCS2103DeleteSequenceDiagram.jpg
  docs/images/AceCS2103LogicClassDiagram.jpg
Labels: type.documentation

#278 Edit AboutUs
  docs/AboutUs.md
Labels: type.documentation

#279 Fix AboutUs
  docs/AboutUs.md
Labels: type.documentation

#281 Update About us
  docs/AboutUs.md
Labels: enhancement

#282 Fix Readme
  README.md
Labels: type.documentation

#285 Fix Documentation
  docs/AboutUs.md
  docs/UserGuide.md
Labels: type.documentation

#293 Fix build bugs
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AceCS2103DeleteSequenceDiagram.jpg
  docs/images/AceCS2103LogicClassDiagram.jpg
  docs/team/onglijin.md
  docs/team/perpetual09.md
  docs/team/xia-liyi.md
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/resources/view/Style.css
  src/test/java/tp/acecs2103/commons/core/ConfigTest.java
  src/test/java/tp/acecs2103/commons/util/AppUtilTest.java
  src/test/java/tp/acecs2103/commons/util/CollectionUtilTest.java
  src/test/java/tp/acecs2103/commons/util/ConfigUtilTest.java
  src/test/java/tp/acecs2103/commons/util/FileUtilTest.java
  src/test/java/tp/acecs2103/commons/util/JsonUtilTest.java
  src/test/java/tp/acecs2103/commons/util/StringUtilTest.java
  src/test/java/tp/acecs2103/logic/parser/DeadlineCommandParserTest.java
  src/test/java/tp/acecs2103/model/UiTaskListTest.java
  src/test/java/tp/acecs2103/testutil/SerializableTestClass.java
  src/test/java/tp/acecs2103/testutil/TestUtil.java
Labels: enhancement

#295 Unicorn jin patch 1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/tp/acecs2103/commons/core/index/Index.java
  src/main/java/tp/acecs2103/logic/parser/ParserUtil.java
  src/main/java/tp/acecs2103/logic/parser/TaskListParser.java
  src/test/java/tp/acecs2103/logic/parser/FilterCommandParserTest.java
Labels: type.documentation

#313 Fix padding bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/zhang-yunjie.md
  src/main/java/tp/acecs2103/commons/core/index/Index.java
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/parser/ParserUtil.java
  src/main/java/tp/acecs2103/logic/parser/TaskListParser.java
  src/main/java/tp/acecs2103/model/task/Index.java
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/Style.css
  src/main/resources/view/TaskBox.fxml
  src/test/java/tp/acecs2103/logic/parser/FilterCommandParserTest.java
Labels: enhancement

#314 Fix padding bug
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/Style.css
  src/main/resources/view/TaskBox.fxml
Labels: enhancement

#315 Fix Ui.png
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/w13.png
Labels: type.documentation

#319 Unicorn jin patch 1
  docs/DeveloperGuide.md
Labels: type.documentation
