Repository AY2021S1-CS2103-T14-4/tp, pull requests merged in 2020-10, with the labels that each got.

#51 Update Clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: priority.low, type.task

#75 Add CategoryBox, TaskBox, and CategoryPanel. The height and width have not set yet
  src/main/java/seedu/address/model/Task.java
  src/main/java/seedu/address/model/TaskCategory.java
  src/main/java/seedu/address/ui/CategoryBox.java
  src/main/java/seedu/address/ui/CategoryPanel.java
  src/main/java/seedu/address/ui/TaskBox.java
  src/main/java/seedu/address/ui/WeekWindow.java
  src/main/resources/view/CategoryBox.fxml
  src/main/resources/view/CategoryList.fxml
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.fxml
  src/main/resources/view/WeekWindow.fxml
Labels: priority.medium

#84 Add CategoryBox, CategoryPanel, TaskBox
  src/main/java/tp/acecs2103/ui/CategoryBox.java
  src/main/java/tp/acecs2103/ui/CategoryPanel.java
  src/main/java/tp/acecs2103/ui/TaskBox.java
  src/main/resources/view/CategoryBox.fxml
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/TaskBox.fxml
Labels: priority.medium

#85 Modify Command package and related classes
  docs/UserGuide.md
  src/main/java/tp/acecs2103/commons/core/Messages.java
  src/main/java/tp/acecs2103/commons/core/index/Index.java
  src/main/java/tp/acecs2103/logic/Logic.java
  src/main/java/tp/acecs2103/logic/LogicManager.java
  src/main/java/tp/acecs2103/logic/commands/AddCommand.java
  src/main/java/tp/acecs2103/logic/commands/DeadlineCommand.java
  src/main/java/tp/acecs2103/logic/commands/DeleteCommand.java
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/commands/ExitCommand.java
  src/main/java/tp/acecs2103/logic/commands/FindCommand.java
  src/main/java/tp/acecs2103/logic/commands/GetCommand.java
  src/main/java/tp/acecs2103/logic/commands/ListCommand.java
  src/main/java/tp/acecs2103/model/Model.java
  src/main/java/tp/acecs2103/model/ModelManager.java
  src/main/java/tp/acecs2103/model/TaskList.java
  src/main/java/tp/acecs2103/model/UiTaskList.java
  src/main/java/tp/acecs2103/model/task/Task.java
  src/main/java/tp/acecs2103/model/task/TaskCategory.java
Labels: priority.medium, type.task

#88 Update UI
  src/main/java/tp/acecs2103/ui/CategoryPanel.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/java/tp/acecs2103/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WeekDisplay.fxml
  src/test/java/tp/acecs2103/commons/util/AppUtilTest.java
Labels: type.task

#97 Fix bug in CategoryBox and TaskBox, improve basic UI desgin
  src/main/java/tp/acecs2103/ui/CategoryBox.java
  src/main/java/tp/acecs2103/ui/CategoryPanel.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/java/tp/acecs2103/ui/TaskBox.java
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.fxml
Labels: priority.medium

#102 Edit WeekDisplay, add css file for TaskBox
  docs/UserGuide.md
  src/main/java/tp/acecs2103/MainApp.java
  src/main/java/tp/acecs2103/commons/core/LogsCenter.java
  src/main/java/tp/acecs2103/commons/core/index/Index.java
  src/main/java/tp/acecs2103/logic/commands/AddCommand.java
  src/main/java/tp/acecs2103/logic/commands/ClearCommand.java
  src/main/java/tp/acecs2103/logic/commands/DeleteCommand.java
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/parser/AddCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/CliSyntax.java
  src/main/java/tp/acecs2103/logic/parser/EditCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ListCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ParserUtil.java
  src/main/java/tp/acecs2103/model/ModelManager.java
  src/main/java/tp/acecs2103/model/TaskList.java
  src/main/java/tp/acecs2103/model/task/Task.java
  src/main/java/tp/acecs2103/model/task/TaskCategory.java
  src/main/java/tp/acecs2103/storage/JsonAdaptedTask.java
  src/main/java/tp/acecs2103/ui/CategoryPanel.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/java/tp/acecs2103/ui/TaskBox.java
  src/main/java/tp/acecs2103/ui/WeekDisplay.java
  src/main/resources/view/CategoryBox.fxml
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.css
  src/main/resources/view/TaskBox.fxml
  src/main/resources/view/WeekDisplay.fxml
Labels: priority.medium

#103 Edit WeekDisplay, add css file for TaskBox
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/java/tp/acecs2103/ui/WeekDisplay.java
  src/main/resources/view/CategoryBox.fxml
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.css
  src/main/resources/view/TaskBox.fxml
  src/main/resources/view/WeekDisplay.fxml
Labels: priority.medium

#111 Fix checkStyleTest error
  src/main/java/tp/acecs2103/model/UiTaskList.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/java/tp/acecs2103/ui/WeekDisplay.java
  src/test/java/ExitCommandTest.java
Labels: priority.medium

#118 Enable assertions for build.gradle
  build.gradle
Labels: type.task

#127 Update Developer Guide for UI Component
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.documentation

#130 Update DG UI enhancement
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/tp/acecs2103/logic/commands/DeadlineCommand.java
  src/main/java/tp/acecs2103/model/TaskList.java
  src/main/java/tp/acecs2103/model/task/Task.java
  src/main/resources/view/CategoryBox.fxml
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskBox.fxml
  src/main/resources/view/WeekDisplay.fxml
  src/test/java/tp/acecs2103/logic/commands/DeadlineCommandTest.java
Labels: enhancement

#131 Update DG UI enhancement
  docs/DeveloperGuide.md
Labels: enhancement

#138 Edit DG: Add Logic component
  docs/DeveloperGuide.md
  docs/images/Ace2103DeleteSequenceDiagram.jpg
  docs/images/Ace2103LogicClassDiagram.jpg
Labels: type.documentation

#139 Add feedback box
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.ngm
  docs/diagrams/StorageClassDiagram.ngm
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/parser/AddCommandParser.java
  src/main/java/tp/acecs2103/model/Model.java
  src/main/java/tp/acecs2103/model/ModelManager.java
  src/main/java/tp/acecs2103/model/TaskList.java
  src/main/java/tp/acecs2103/model/exceptions/InvalidTaskListOperationException.java
  src/main/java/tp/acecs2103/model/exceptions/ModelException.java
  src/main/java/tp/acecs2103/model/task/Admin.java
  src/main/java/tp/acecs2103/model/task/IP.java
  src/main/java/tp/acecs2103/model/task/TP.java
  src/main/java/tp/acecs2103/model/task/Task.java
  src/main/java/tp/acecs2103/model/task/Topic.java
  src/main/java/tp/acecs2103/model/util/SampleDataUtil.java
  src/main/java/tp/acecs2103/storage/JsonAdaptedTask.java
  src/main/java/tp/acecs2103/ui/CategoryBox.java
  src/main/java/tp/acecs2103/ui/FeedbackBox.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/resources/view/FeedbackBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/tp/acecs2103/logic/commands/DeadlineCommandTest.java
Labels: enhancement, priority.medium

#141 Add feedback box
  src/main/java/tp/acecs2103/ui/CategoryBox.java
  src/main/java/tp/acecs2103/ui/FeedbackBox.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/resources/view/FeedbackBox.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.medium

#142 Refactor Model
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/tp/acecs2103/MainApp.java
  src/main/java/tp/acecs2103/commons/util/AppUtil.java
  src/main/java/tp/acecs2103/logic/commands/DeadlineCommand.java
  src/main/java/tp/acecs2103/logic/commands/DeleteCommand.java
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/commands/ListCommand.java
  src/main/java/tp/acecs2103/logic/parser/AddCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/CliSyntax.java
  src/main/java/tp/acecs2103/logic/parser/DeadlineCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DeleteCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/EditCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ListCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ParserUtil.java
  src/main/java/tp/acecs2103/model/AddressBook.java
  src/main/java/tp/acecs2103/model/ModelManager.java
  src/main/java/tp/acecs2103/model/ReadOnlyAddressBook.java
  src/main/java/tp/acecs2103/model/TaskList.java
  src/main/java/tp/acecs2103/model/UiTaskList.java
  src/main/java/tp/acecs2103/model/task/Address.java
  src/main/java/tp/acecs2103/model/task/Admin.java
  src/main/java/tp/acecs2103/model/task/CustomizedDeadline.java
  src/main/java/tp/acecs2103/model/task/Description.java
  src/main/java/tp/acecs2103/model/task/Email.java
  src/main/java/tp/acecs2103/model/task/IP.java
  src/main/java/tp/acecs2103/model/task/Index.java
  src/main/java/tp/acecs2103/model/task/Name.java
  src/main/java/tp/acecs2103/model/task/NameContainsKeywordsPredicate.java
  src/main/java/tp/acecs2103/model/task/OfficialDeadline.java
  src/main/java/tp/acecs2103/model/task/Person.java
  src/main/java/tp/acecs2103/model/task/Phone.java
  src/main/java/tp/acecs2103/model/task/Remark.java
  src/main/java/tp/acecs2103/model/task/TP.java
  src/main/java/tp/acecs2103/model/task/Task.java
  src/main/java/tp/acecs2103/model/task/Topic.java
  src/main/java/tp/acecs2103/model/task/UniquePersonList.java
  src/main/java/tp/acecs2103/model/task/WeekNumber.java
  src/main/java/tp/acecs2103/model/util/SampleDataUtil.java
  src/main/java/tp/acecs2103/storage/AddressBookStorage.java
  src/main/java/tp/acecs2103/storage/JsonAdaptedPerson.java
  src/main/java/tp/acecs2103/storage/JsonAdaptedTask.java
  src/main/java/tp/acecs2103/storage/JsonAddressBookStorage.java
  src/main/java/tp/acecs2103/storage/JsonSerializableAddressBook.java
  src/main/java/tp/acecs2103/storage/StorageManager.java
  src/main/java/tp/acecs2103/ui/PersonCard.java
  src/main/java/tp/acecs2103/ui/PersonListPanel.java
  src/main/java/tp/acecs2103/ui/TaskBox.java
Labels: enhancement

#153 Update DG
  docs/DeveloperGuide.md
Labels: type.documentation

#156 Unicorn jin patch 1
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/commands/FilterCommand.java
  src/main/java/tp/acecs2103/logic/commands/ListCommand.java
  src/main/java/tp/acecs2103/logic/parser/AddCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/ArgumentMultimap.java
  src/main/java/tp/acecs2103/logic/parser/CliSyntax.java
  src/main/java/tp/acecs2103/logic/parser/DeadlineCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DoneCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/EditCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/FilterCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/Parser.java
  src/main/java/tp/acecs2103/logic/parser/TaskListParser.java
  src/main/java/tp/acecs2103/logic/parser/UndoneCommandParser.java
  src/main/java/tp/acecs2103/model/TaskList.java
  src/main/java/tp/acecs2103/model/task/OfficialDeadline.java
  src/main/java/tp/acecs2103/model/task/Task.java
  src/main/java/tp/acecs2103/model/task/WeekNumber.java
  src/main/java/tp/acecs2103/model/util/SampleDataUtil.java
  src/main/java/tp/acecs2103/storage/JsonAdaptedTask.java
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WeekDisplay.fxml
Labels: enhancement

#160 Perpetual09 patch 1
  src/main/java/tp/acecs2103/ui/CategoryPanel.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/resources/view/CategoryPanel.fxml
  src/main/resources/view/FeedbackBox.fxml
  src/main/resources/view/TaskBox.css
  src/main/resources/view/TaskBox.fxml
Labels: priority.medium

#161 Update UserGuide
  docs/UserGuide.md
Labels: type.documentation

#164 Update UG
  docs/UserGuide.md
  src/main/java/tp/acecs2103/logic/commands/AddCommand.java
  src/main/java/tp/acecs2103/logic/commands/DeadlineCommand.java
  src/main/java/tp/acecs2103/logic/commands/DoneCommand.java
  src/main/java/tp/acecs2103/logic/commands/EditCommand.java
  src/main/java/tp/acecs2103/logic/commands/FilterCommand.java
  src/main/java/tp/acecs2103/logic/commands/HelpCommand.java
  src/main/java/tp/acecs2103/logic/commands/UndoneCommand.java
  src/main/java/tp/acecs2103/logic/parser/AddCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/DoneCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/EditCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/FilterCommandParser.java
  src/main/java/tp/acecs2103/logic/parser/TaskListParser.java
  src/main/java/tp/acecs2103/logic/parser/UndoneCommandParser.java
  src/main/java/tp/acecs2103/model/Model.java
  src/main/java/tp/acecs2103/model/ModelManager.java
  src/main/java/tp/acecs2103/model/TaskList.java
  src/main/java/tp/acecs2103/model/task/Admin.java
  src/main/java/tp/acecs2103/model/task/CustomizedDeadline.java
  src/main/java/tp/acecs2103/model/task/Deadline.java
  src/main/java/tp/acecs2103/model/task/IP.java
  src/main/java/tp/acecs2103/model/task/TP.java
  src/main/java/tp/acecs2103/model/task/Task.java
  src/main/java/tp/acecs2103/model/task/WeekNumber.java
  src/main/java/tp/acecs2103/model/util/SampleDataUtil.java
  src/main/java/tp/acecs2103/storage/JsonAdaptedTask.java
  src/main/java/tp/acecs2103/ui/CategoryPanel.java
  src/main/java/tp/acecs2103/ui/MainWindow.java
  src/main/java/tp/acecs2103/ui/TaskBox.java
  src/main/java/tp/acecs2103/ui/WeekDisplay.java
  src/main/resources/view/TaskBox.css
  src/main/resources/view/TaskBox.fxml
  src/test/java/tp/acecs2103/logic/commands/DeadlineCommandTest.java
Labels: priority.medium

#165 Update UG
  docs/UserGuide.md
Labels: priority.medium
